language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install nose unittest2 mock --use-mirrors
    - pip install . --use-mirrors
script: nosetests -s browserid
notifications:
    irc:
        channels: 
            - "irc.mozilla.org#services-dev"
        on_success: change
